on: [push, pull_request]
name: lint
jobs:
  lint-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: docker://avtodev/markdown-lint:v1 # fastest way
        with:
          args: "./*.md"
